package uz.developers.user

enum class ErrorCodes(val code: Int) {
    VALIDATION_ERROR(40),
    USER_PENDING(20),
    USER_BLOCKED(30),
    USERNAME_ALREADY_TAKEN(100),
    GENERAL_API_EXCEPTION(101),
    OLD_PASSWORD_ERROR(103),
    ACCESS_DENIED(105),
    FEIGN_ERROR(106),


    USER_NOT_FOUND(100),
    USER_ALREADY_EXISTS(101),
    INCORRECT_PASSWORD(102),
    ID_IS_REQUIRED(103),
    ROLE_NOT_FOUND(104),
    ROLE_ALREADY_EXISTS(105),
    INVALID_AMOUNT(106)
}


enum class UserStatus {
    INACTIVE,
    BLOCKED,
    ACTIVE,
    PENDING
}
